version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: class_central_postgres_server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: class_central
      POSTGRES_PASSWORD: class_central
      POSTGRES_DB: class_central
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

